"""initial_schema

Revision ID: cf3b67c461e7
Revises: 
Create Date: 2026-06-27 10:47:41.944077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3b67c461e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('CategoryID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CategoryName', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('CategoryID')
    )
    op.create_table('Customers',
    sa.Column('CustomerID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CompanyName', sa.Text(), nullable=True),
    sa.Column('CompanyOrDepartment', sa.Text(), nullable=True),
    sa.Column('ContactFirstName', sa.Text(), nullable=True),
    sa.Column('ContactLastName', sa.Text(), nullable=True),
    sa.Column('ContactTitle', sa.Text(), nullable=True),
    sa.Column('BillingAddress', sa.Text(), nullable=True),
    sa.Column('City', sa.Text(), nullable=True),
    sa.Column('StateOrProvince', sa.Text(), nullable=True),
    sa.Column('PostalCode', sa.Text(), nullable=True),
    sa.Column('Country/Region', sa.Text(), nullable=True),
    sa.Column('PhoneNumber', sa.Text(), nullable=True),
    sa.Column('FaxNumber', sa.Text(), nullable=True),
    sa.Column('Extension', sa.Text(), nullable=True),
    sa.Column('EmailAddress', sa.Text(), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('CustomerID')
    )
    op.create_table('Levels',
    sa.Column('Level', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('Level')
    )
    op.create_table('Providers',
    sa.Column('ProviderID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProviderName', sa.Text(), nullable=True),
    sa.Column('ContactFirstName', sa.Text(), nullable=True),
    sa.Column('ContactLastName', sa.Text(), nullable=True),
    sa.Column('ContactTitle', sa.Text(), nullable=True),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.Column('City', sa.Text(), nullable=True),
    sa.Column('StateOrProvince', sa.Text(), nullable=True),
    sa.Column('PostalCode', sa.Text(), nullable=True),
    sa.Column('Country/Region', sa.Text(), nullable=True),
    sa.Column('PhoneNumber', sa.Text(), nullable=True),
    sa.Column('FaxNumber', sa.Text(), nullable=True),
    sa.Column('Extension', sa.Text(), nullable=True),
    sa.Column('EmailAddress', sa.Text(), nullable=True),
    sa.Column('PaymentTerms', sa.Text(), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ProviderID')
    )
    op.create_table('OrderReceptions',
    sa.Column('OrderID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProviderID', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Text(), nullable=True),
    sa.Column('OrderDate', sa.Text(), nullable=True),
    sa.Column('RequiredByDate', sa.Text(), nullable=True),
    sa.Column('PromisedByDate', sa.Text(), nullable=True),
    sa.Column('ReceivedBy', sa.Text(), nullable=True),
    sa.Column('FreightCharge', sa.Float(), nullable=True),
    sa.Column('SalesTaxRate', sa.Float(), nullable=True),
    sa.Column('PurchaseOrderNumber', sa.Text(), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.Column('ChangedBy', sa.Text(), nullable=True),
    sa.Column('ChangedDate', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ProviderID'], ['Providers.ProviderID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('OrderRequests',
    sa.Column('OrderID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Text(), nullable=True),
    sa.Column('OrderDate', sa.Text(), nullable=True),
    sa.Column('RequiredByDate', sa.Text(), nullable=True),
    sa.Column('PromisedByDate', sa.Text(), nullable=True),
    sa.Column('ShipDate', sa.Text(), nullable=True),
    sa.Column('ShipName', sa.Text(), nullable=True),
    sa.Column('ShipAddress', sa.Text(), nullable=True),
    sa.Column('ShipCity', sa.Text(), nullable=True),
    sa.Column('ShipState', sa.Text(), nullable=True),
    sa.Column('ShipStateOrProvince', sa.Text(), nullable=True),
    sa.Column('ShipPostalCode', sa.Text(), nullable=True),
    sa.Column('ShipCountry', sa.Text(), nullable=True),
    sa.Column('ShipPhoneNumber', sa.Text(), nullable=True),
    sa.Column('ShippingMethodID', sa.Integer(), nullable=True),
    sa.Column('FreightCharge', sa.Float(), nullable=True),
    sa.Column('SalesTaxRate', sa.Float(), nullable=True),
    sa.Column('PurchaseOrderNumber', sa.Text(), nullable=True),
    sa.Column('EmployeeID', sa.Text(), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.Column('ChangedBy', sa.Text(), nullable=True),
    sa.Column('ChangedDate', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('Products',
    sa.Column('ProductID', sa.Text(), nullable=False),
    sa.Column('ProductName', sa.Text(), nullable=True),
    sa.Column('ProductDescription', sa.Text(), nullable=True),
    sa.Column('SupplierID', sa.Integer(), nullable=True),
    sa.Column('CategoryID', sa.Integer(), nullable=True),
    sa.Column('UnitPrice', sa.Float(), nullable=True),
    sa.Column('QuantityPerUnit', sa.Float(), nullable=True),
    sa.Column('Unit', sa.Text(), nullable=True),
    sa.Column('UnitsInStock', sa.Integer(), nullable=True),
    sa.Column('UnitsOnOrder', sa.Integer(), nullable=True),
    sa.Column('ReorderLevel', sa.Integer(), nullable=True),
    sa.Column('Discontinued', sa.Integer(), nullable=False),
    sa.Column('LeadTime', sa.Text(), nullable=True),
    sa.Column('SerialNumber', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['CategoryID'], ['Categories.CategoryID'], ),
    sa.ForeignKeyConstraint(['SupplierID'], ['Providers.ProviderID'], ),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('Users',
    sa.Column('Username', sa.Text(), nullable=False),
    sa.Column('Password', sa.Text(), nullable=True),
    sa.Column('Fullname', sa.Text(), nullable=True),
    sa.Column('Level', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['Level'], ['Levels.Level'], ),
    sa.PrimaryKeyConstraint('Username')
    )
    op.create_table('OrderReceptionDetails',
    sa.Column('OrderDetailID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=True),
    sa.Column('ProductID', sa.Text(), nullable=True),
    sa.Column('Quantity', sa.Float(), nullable=True),
    sa.Column('UnitPrice', sa.Float(), nullable=True),
    sa.Column('SalePrice', sa.Float(), nullable=True),
    sa.Column('Discount', sa.Float(), nullable=True),
    sa.Column('SalesTax', sa.Float(), nullable=True),
    sa.Column('LineTotal', sa.Float(), nullable=True),
    sa.Column('DateSold', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['OrderID'], ['OrderReceptions.OrderID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.PrimaryKeyConstraint('OrderDetailID')
    )
    op.create_table('OrderRequestDetails',
    sa.Column('OrderDetailID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=True),
    sa.Column('ProductID', sa.Text(), nullable=True),
    sa.Column('Quantity', sa.Float(), nullable=True),
    sa.Column('UnitPrice', sa.Float(), nullable=True),
    sa.Column('SalePrice', sa.Float(), nullable=True),
    sa.Column('Discount', sa.Float(), nullable=True),
    sa.Column('SalesTax', sa.Float(), nullable=True),
    sa.Column('LineTotal', sa.Float(), nullable=True),
    sa.Column('DateSold', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['OrderID'], ['OrderRequests.OrderID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.PrimaryKeyConstraint('OrderDetailID')
    )
    op.create_table('ProductsByCustomer',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('ProductsByProvider',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProviderID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.ForeignKeyConstraint(['ProviderID'], ['Providers.ProviderID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Stocks',
    sa.Column('StockID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProductID', sa.Text(), nullable=True),
    sa.Column('Stock', sa.Float(), nullable=True),
    sa.Column('InitialStock', sa.Float(), nullable=True),
    sa.Column('UnitPrice', sa.Float(), nullable=True),
    sa.Column('StockPrice', sa.Float(), nullable=True),
    sa.Column('DateStarted', sa.Text(), nullable=True),
    sa.Column('DateModified', sa.Text(), nullable=True),
    sa.Column('User', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.PrimaryKeyConstraint('StockID')
    )
    op.create_table('ManualStocks',
    sa.Column('ManualID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StockID', sa.Integer(), nullable=True),
    sa.Column('Action', sa.Text(), nullable=True),
    sa.Column('Quantity', sa.Float(), nullable=True),
    sa.Column('Price', sa.Float(), nullable=True),
    sa.Column('Date', sa.Text(), nullable=True),
    sa.Column('User', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['StockID'], ['Stocks.StockID'], ),
    sa.PrimaryKeyConstraint('ManualID')
    )
    op.create_table('StockLog',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StockID', sa.Integer(), nullable=True),
    sa.Column('ProductID', sa.Text(), nullable=True),
    sa.Column('DocType', sa.Text(), nullable=True),
    sa.Column('DocID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Float(), nullable=True),
    sa.Column('StockPrice', sa.Float(), nullable=True),
    sa.Column('Date', sa.Text(), nullable=True),
    sa.Column('User', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.ForeignKeyConstraint(['StockID'], ['Stocks.StockID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StockLog')
    op.drop_table('ManualStocks')
    op.drop_table('Stocks')
    op.drop_table('ProductsByProvider')
    op.drop_table('ProductsByCustomer')
    op.drop_table('OrderRequestDetails')
    op.drop_table('OrderReceptionDetails')
    op.drop_table('Users')
    op.drop_table('Products')
    op.drop_table('OrderRequests')
    op.drop_table('OrderReceptions')
    op.drop_table('Providers')
    op.drop_table('Levels')
    op.drop_table('Customers')
    op.drop_table('Categories')
    # ### end Alembic commands ###
